name: Windows

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ main ]


env:
   ARCH: "x64"
   LANGUAGE: "English International"
   WINDOWS: "10"
   VERSION: "19045.2006" # a.k.a 22H2

jobs:
  Extract:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install python packages
      run: pip3 install -r requirements.txt

    - name: Download Windows ISO
      run: python3 download.py -w "${{ env.WINDOWS }}" -v "${{ env.VERSION }}" -l "${{ env.LANGUAGE }}" -a "${{ env.ARCH }}"

    - name: Windows ISO Checksum
      run: |
        Get-FileHash -Algorithm SHA1 -Path win.iso
        Get-FileHash -Algorithm SHA256 -Path win.iso

    - name: Extract install.wim
      run: |
        Mount-DiskImage -ImagePath $pwd\win.iso
        copy E:\sources\install.wim .
        Dismount-DiskImage -ImagePath $pwd\win.iso
        del .\win.iso

    - name: Show Available Editions
      run: |
        Dism /Get-ImageInfo /ImageFile:install.wim

    - name: Extract Boot Files Home Edition
      run: |
        $BASE_FILENAME = "Windows${{ env.WINDOWS }}_${{ env.VERSION }}_${{ env.LANGUAGE }}_${{ env.ARCH }}_Home"
        mkdir mount
        Dism /Mount-Image /ImageFile:install.wim /Index:1 /MountDir:$pwd/mount /ReadOnly /optimize
        Get-FileHash -Algorithm SHA256 -Path (Get-ChildItem ".\mount\Windows\Boot\*.*" -Recurse) > .\hash.sha256
        Compress-Archive .\mount\Windows\Boot\ , .\hash.sha256 "${BASE_FILENAME}.zip"
        Get-FileHash -Algorithm SHA256 -Path "${BASE_FILENAME}.zip" > "${BASE_FILENAME}.zip.sha256"
        Dism /Unmount-Image /MountDir:mount /discard
        del mount

    - name: Extract Boot Files Pro Edition
      run: |
        $BASE_FILENAME = "Windows${{ env.WINDOWS }}_${{ env.VERSION }}_${{ env.LANGUAGE }}_${{ env.ARCH }}_Pro"
        mkdir mount
        Dism /Mount-Image /ImageFile:install.wim /Index:6 /MountDir:$pwd/mount /ReadOnly /optimize
        Get-FileHash -Algorithm SHA256 -Path (Get-ChildItem ".\mount\Windows\Boot\*.*" -Recurse) > .\hash.sha256
        Compress-Archive .\mount\Windows\Boot\ , .\hash.sha256 "${BASE_FILENAME}.zip"
        Get-FileHash -Algorithm SHA256 -Path "${BASE_FILENAME}.zip" > "${BASE_FILENAME}.zip.sha256"
        Dism /Unmount-Image /MountDir:mount /discard
        del mount

    - name: Extract Font Files Pro Edition
      run: |
        $BASE_FILENAME = "Windows${{ env.WINDOWS }}_${{ env.VERSION }}_${{ env.LANGUAGE }}_${{ env.ARCH }}_Fonts"
        mkdir mount
        Dism /Mount-Image /ImageFile:install.wim /Index:6 /MountDir:$pwd/mount /ReadOnly /optimize
        Get-FileHash -Algorithm SHA256 -Path (Get-ChildItem ".\mount\Windows\Fonts\*.*") > .\hash.sha256
        Compress-Archive .\mount\Windows\Fonts\ , .\hash.sha256 "${BASE_FILENAME}.zip"
        Get-FileHash -Algorithm SHA256 -Path "${BASE_FILENAME}.zip" > "${BASE_FILENAME}.zip.sha256"
        Dism /Unmount-Image /MountDir:mount /discard
        del mount

    - name: List Created Files
      shell: bash
      run: ls -lh *.zip.sha256 *.zip

    - name: Release Files
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: "Windows ${{ env.WINDOWS }} ${{ env.VERSION }} ${{ env.LANGUAGE }} ${{ env.ARCH }} Files"
        files: |
          ./*.zip.sha256
          ./*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
