name: Windows

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ main ]


env:
   ARCH: "x64"
   LANGUAGE: "English International"
   WINDOWS: "11"
   BUILD: "22621.525"
   VERSION: "22H2"

jobs:
  Extract:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install python packages
      run: pip3 install -r requirements.txt

    - name: Download Windows ISO
      run: python3 download.py -w "${{ env.WINDOWS }}" -v "${{ env.BUILD }}" -l "${{ env.LANGUAGE }}" -a "${{ env.ARCH }}"

    - name: Windows ISO Checksum
      run: |
        Get-FileHash -Algorithm SHA1 -Path win.iso
        Get-FileHash -Algorithm SHA256 -Path win.iso

    - name: Extract install.wim
      run: |
        Mount-DiskImage -ImagePath $pwd\win.iso
        copy E:\sources\install.wim .
        Dismount-DiskImage -ImagePath $pwd\win.iso
        del .\win.iso

    - name: Show Available Editions
      run: |
        Dism /Get-ImageInfo /ImageFile:install.wim

    - name: Create Output Directory
      run: mkdir output_dir

    - name: Extract Boot Files Home Edition
      run: |
        $BASE_FILENAME = "Windows${{ env.WINDOWS }}_${{ env.VERSION }}_${{ env.LANGUAGE }}_${{ env.ARCH }}_Home"
        mkdir mount
        Dism /Mount-Image /ImageFile:install.wim /Index:1 /MountDir:$pwd/mount /ReadOnly /optimize
        Get-FileHash -Algorithm SHA256 -Path (Get-ChildItem ".\mount\Windows\Boot\*.*" -Recurse) > .\output_dir\hash.sha256
        Compress-Archive .\mount\Windows\Boot\ , .\output_dir\hash.sha256 ".\output_dir\${BASE_FILENAME}.zip"
        Get-FileHash -Algorithm SHA256 -Path ".\output_dir\${BASE_FILENAME}.zip" > ".\output_dir\${BASE_FILENAME}.zip.sha256"
        Dism /Unmount-Image /MountDir:mount /discard
        del mount

    - name: Extract Boot Files Pro Edition
      run: |
        $BASE_FILENAME = "Windows${{ env.WINDOWS }}_${{ env.VERSION }}_${{ env.LANGUAGE }}_${{ env.ARCH }}_Pro"
        mkdir mount
        Dism /Mount-Image /ImageFile:install.wim /Index:6 /MountDir:$pwd/mount /ReadOnly /optimize
        Get-FileHash -Algorithm SHA256 -Path (Get-ChildItem ".\mount\Windows\Boot\*.*" -Recurse) > .\output_dir\hash.sha256
        Compress-Archive .\mount\Windows\Boot\ , .\output_dir\hash.sha256 ".\output_dir\${BASE_FILENAME}.zip"
        Get-FileHash -Algorithm SHA256 -Path ".\output_dir\${BASE_FILENAME}.zip" > ".\output_dir\${BASE_FILENAME}.zip.sha256"
        Dism /Unmount-Image /MountDir:mount /discard
        del mount

    - name: Extract Font Files Pro Edition
      run: |
        $BASE_FILENAME = "Windows${{ env.WINDOWS }}_${{ env.VERSION }}_${{ env.LANGUAGE }}_${{ env.ARCH }}_Fonts"
        mkdir mount
        Dism /Mount-Image /ImageFile:install.wim /Index:6 /MountDir:$pwd/mount /ReadOnly /optimize
        Get-FileHash -Algorithm SHA256 -Path (Get-ChildItem ".\mount\Windows\Fonts\*.*") > .\output_dir\hash.sha256
        Compress-Archive .\mount\Windows\Fonts\ , .\output_dir\hash.sha256 ".\output_dir\${BASE_FILENAME}.zip"
        Get-FileHash -Algorithm SHA256 -Path ".\output_dir\${BASE_FILENAME}.zip" > ".\output_dir\${BASE_FILENAME}.zip.sha256"
        Dism /Unmount-Image /MountDir:mount /discard
        del mount

    - name: List Created Files
      shell: bash
      run: ls -lh ./output_dir

    - name: Release Files
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: "Windows ${{ env.WINDOWS }} ${{ env.VERSION }} (build ${{ env.BUILD }}) ${{ env.LANGUAGE }} ${{ env.ARCH }} Files"
        files: |
          ./output_dir/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
