name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Selenium
      run: pip3 install selenium

    - name: Download Windows ISO
      run: python3 download.py -v 20H1

  test_windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Selenium
      run: pip3 install selenium

    - name: Install wget
      run: choco install wget

    - name: Download Windows ISO
      run: python3 download.py -v 20H1
