name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
   ARCH: "x64"
   LANGUAGE: "English International"
   VERSION: "20H2"

jobs:
  Extract:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Selenium
      run: pip3 install selenium

    - name: Download Windows ISO
      run: python3 download.py -v ${{ env.VERSION }} -l ${{ env.LANGUAGE }} -a ${{ env.ARCH }}"

    - name: Windows ISO Checksum
      run: |
        Get-FileHash -Algorithm SHA1 -Path win.iso
        Get-FileHash -Algorithm SHA256 -Path win.iso

    - name: Extract install.wim
      run: |
        Mount-DiskImage -ImagePath $pwd\win.iso
        copy E:\sources\install.wim .
        Dismount-DiskImage -ImagePath $pwd\win.iso
        del .\win.iso

    - name: Show Available Editions
      run: |
        Dism /Get-ImageInfo /ImageFile:install.wim

    - name: Extract Boot Files Home Edition
      run: |
        $BASE_FILENAME = "Windows10_${{ env.VERSION }}_${{ env.LANGUAGE }}_${{ env.ARCH }}_Home"
        mkdir mount
        Dism /Mount-Image /ImageFile:install.wim /Index:1 /MountDir:$pwd/mount /ReadOnly /optimize
        Get-FileHash -Algorithm SHA256 -Path (Get-ChildItem ".\mount\Windows\Boot\*.*" -Recurse) > .\hash.sha256
        Compress-Archive .\mount\Windows\Boot\ , .\hash.sha256 "${BASE_FILENAME}.zip"
        Get-FileHash -Algorithm SHA256 -Path "${BASE_FILENAME}.zip" > "${BASE_FILENAME}.zip.sha256"
        Dism /Unmount-Image /MountDir:mount /discard
        del mount

    - name: Extract Boot Files Pro Edition
      run: |
        $BASE_FILENAME = "Windows10_${{ env.VERSION }}_${{ env.LANGUAGE }}_${{ env.ARCH }}_Pro"
        mkdir mount
        Dism /Mount-Image /ImageFile:install.wim /Index:6 /MountDir:$pwd/mount /ReadOnly /optimize
        Get-FileHash -Algorithm SHA256 -Path (Get-ChildItem ".\mount\Windows\Boot\*.*" -Recurse) > .\hash.sha256
        Compress-Archive .\mount\Windows\Boot\ , .\hash.sha256 "${BASE_FILENAME}.zip"
        Get-FileHash -Algorithm SHA256 -Path "${BASE_FILENAME}.zip" > "${BASE_FILENAME}.zip.sha256"
        Dism /Unmount-Image /MountDir:mount /discard
        del mount

    - name: Extract Font Files Pro Edition
      run: |
        $BASE_FILENAME = "Windows10_${{ env.VERSION }}_${{ env.LANGUAGE }}_${{ env.ARCH }}_Fonts"
        mkdir mount
        Dism /Mount-Image /ImageFile:install.wim /Index:6 /MountDir:$pwd/mount /ReadOnly /optimize
        Get-FileHash -Algorithm SHA256 -Path (Get-ChildItem ".\mount\Windows\Fonts\*.*") > .\hash.sha256
        Compress-Archive .\mount\Windows\Fonts\ , .\hash.sha256 "${BASE_FILENAME}.zip"
        Get-FileHash -Algorithm SHA256 -Path "${BASE_FILENAME}.zip" > "${BASE_FILENAME}.zip.sha256"
        Dism /Unmount-Image /MountDir:mount /discard
        del mount
